#!/bin/sh
# Test various situations where the signature line is invalid

# In case a previous test did not shutdown the daemon
echo shutdown | socat - TCP:localhost:4455
T=$(basename $0)
SRCDIR=$(dirname $0)

set -e  # stop on first error

./ses 4455 $SRCDIR/test.cert 2>&1 | tee $T.log &
pid=$!
sleep 0.5  # allow time for the server to start

# Test various invalid signature lines
echo "" | socat - TCP:localhost:4455
echo "#" | socat - TCP:localhost:4455
echo "x" | socat - TCP:localhost:4455
echo "# " | socat - TCP:localhost:4455
echo "# 3x" | socat - TCP:localhost:4455
echo "# 3ef" | socat - TCP:localhost:4455

echo shutdown | socat - TCP:localhost:4455

wait $pid

grep "0: authentication FAILED: too short" $T.log >/dev/null
grep "1: authentication FAILED: verification failed" $T.log >/dev/null
grep "2: authentication FAILED: missing '#' as first character" $T.log >/dev/null
grep "3: authentication FAILED: verification failed" $T.log >/dev/null
grep "4: authentication FAILED: cannot get valid signature: -3" $T.log >/dev/null
grep "5: authentication FAILED: cannot get valid signature: -1" $T.log >/dev/null
