#!/bin/sh
# Test executing various scripts

# In case a previous test did not shutdown the daemon
echo shutdown | socat - TCP:localhost:4455
T=$(basename $0)
SRCDIR=$(dirname $0)

set -e  # stop on first error

./ses 4455 $SRCDIR/test.cert 2>&1 | tee $T.log &
pid=$!
sleep 0.5  # allow time for the server to start

# Sending to the server
cat $SRCDIR/script1-exit | socat - TCP:localhost:4455
cat $SRCDIR/script2-sleep-1s | socat - TCP:localhost:4455
cat $SRCDIR/script3-killed | socat - TCP:localhost:4455

sleep 2
echo shutdown | socat - TCP:localhost:4455

wait $pid

# Check
grep "0: child terminated .* error: exit status 1" $T.log >/dev/null
grep "1: output: this is printed on stderr" $T.log >/dev/null
grep "1: output: Script completed" $T.log >/dev/null
grep "2: child terminated .* error: exit status 137" $T.log >/dev/null
