#!/bin/sh
# Test shutdown

set -e  # stop on first error

T=$(basename $0)
SRCDIR=$(dirname $0)

./ses 4455 $SRCDIR/test.cert &
pid=$!
sleep 0.5  # allow time for the server to start

echo shutdown | socat - TCP:localhost:4455

wait $pid
